// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZZ0HeDLyKkaKRxmzRw4168aXKyUdKRo',
    appId: '1:676266261941:web:a7c93d00f224405aeaedfc',
    messagingSenderId: '676266261941',
    projectId: 'jawalingo-c44ea',
    authDomain: 'jawalingo-c44ea.firebaseapp.com',
    storageBucket: 'jawalingo-c44ea.firebasestorage.app',
    measurementId: 'G-1KC57T4B3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoikw0XtPakMNczEe8DammzIbSIJHCh24',
    appId: '1:676266261941:android:fc12c892f338ee4aeaedfc',
    messagingSenderId: '676266261941',
    projectId: 'jawalingo-c44ea',
    storageBucket: 'jawalingo-c44ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HmjDFN4Qanh1L7U60hU15Y-EeZ5C2UU',
    appId: '1:676266261941:ios:b321e607b03bd264eaedfc',
    messagingSenderId: '676266261941',
    projectId: 'jawalingo-c44ea',
    storageBucket: 'jawalingo-c44ea.firebasestorage.app',
    iosBundleId: 'com.jawalingo.jawalingo',
  );
}
